### ISSUE TITLE
Add Toleration to Browsers List

### ISSUE THREAD

**Issue by donofriov** [aerokube/moon#122]
## New Feature Request
Add Toleration support to the Browsers List file so I can have the browser pods connect to a specific node pool.

Currently my node pool has a Taint that will only allow pods to connect to it that have the matching Toleration (https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/). I'm able to add this to my Deployment declaration for the moon pods, but I need the option to add this Toleration to the Browsers List.

```
kind: Deployment
spec:
  template:
    spec:
      tolerations:
        - key: "dedicated"
          value: "selenium"
          operator: "Equal"
          effect: "NoSchedule"
```

Possible New Browser List Setup:
```
"chrome": {
  "default": "71.0",
  "versions": {
    "71.0": {
      "image": "selenoid/vnc_chrome:71.0",
      "port": "4444",
      "nodeSelector": {
        "cloud.google.com/gke-nodepool": "selenium-pool"
      },
      "tolerations": [
        {
          "key": "dedicated",
          "value": "selenium",
          "operator": "Equal",
          "effect": "NoSchedule"
        },
      ],
    },
  }
}
```
