### ISSUE TITLE
Moon should use its own service account for browser pods

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/moon#128]
Should be able to specify service account name or determine it automatically.

**Comment by vania-pooh** [comment]
Could possibly use:
```
        - name: MY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
```
