### ISSUE TITLE
Openshift 3.9 Forbidden to create pod

### ISSUE THREAD

**Issue by conradkirschner** [aerokube/moon#209]
2020/06/05 12:43:59 [FORBIDDEN_TO_CREATE_POD] [browsers] [*****, *.*.*.*] [chrome-81-0-78be0293-f318-48d9-93f6-645e9243349f] [pods "chrome-81-0-78be0293-f318-48d9-93f6-645e9243349f" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{65534}: 65534 is not an allowed group spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 106: must be in the ranges: [1006670000, 1006679999] spec.containers[1].securityContext.securityContext.runAsUser: Invalid value: 106: must be in the ranges: [1006670000, 1006679999]]] [0.01s]

**Comment by vania-pooh** [comment]
@conradkirschner `fsGroup` was fixed in #207 and will be released in next Moon release 1.5.1. For user `uid` currently two possible solutions exist:
1) Allow user ID 106
2) Rebuild browser images with another user ID allowed by Openshift

**Comment by niiku** [comment]
Configure the moon helm chart like the following:
```yaml
  config:
    kernelCaps: []
    runAs:
      # user/group must match a ID from the allowed range
      user: "1000870000" 
      group: "1000870000"
```
this results in a service.json like this:
```json
{ 
  [...]
  "runAs": {
    "user": 1000870000,
    "group": 1000870000
  }
}
```
without a kernelCaps section. With this config, moon can be run in OpenShift without issues (tested on 4.20)
