### ISSUE TITLE
Document network connectivity particularities

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/moon#222]
Using Moon with DNS settings where short domain names are forbidden:
```
  dnsConfig:
    nameservers:
      - 1.2.3.4
    searches:
      - ns1.svc.cluster-domain.example
      - my.dns.search.suffix
```
