### ISSUE TITLE
Chrome image doesn't have correct permissions on all folders under /home/selenium

### ISSUE THREAD

**Issue by andrew-sumner** [aerokube/moon#262]
Our enterprise kubernetes is locked down and we cannot run as root. We are using helm to apply this.

We had a look at the chrome pod and the folders /home/selenium/.fluxbox & Downloads are not owned by the user selenium. 

Can the browser images be updated?

# Setup

I've updated the helm values as follows:

```
  config:
    kernelCaps: []
    runAs:
      user: selenium

  securityContext:
    runAsUser: 1000
```

When we start a test we get these logs from the chrome pod:
```
ChromeDriver was started successfully.
/usr/bin/fbsetbg: 159: /usr/bin/fbsetbg: cannot create /home/selenium/.fluxbox/lastwallpaper.tmp: Permission denied
mv: cannot stat '/home/selenium/.fluxbox/lastwallpaper.tmp': No such file or directory
/usr/bin/fbsetbg: 168: /usr/bin/fbsetbg: cannot create /home/selenium/.fluxbox/lastwallpaper: Permission denied
2021/03/18 20:21:07 [INIT] [Listening on :7070]
```

We had a look and it appears that /home/selenium/.fluxbox & Downloads folders are not owned by the user selenium.
```
selenium@chrome-87-0-55d3a572-a341-4dcc-aee6-57a30ec1d6a8:/home$ ls -lha selenium/
total 4.0K
drwxrwxr-x. 1 selenium root    63 Mar 19 03:04 .
drwxr-xr-x. 1 root     root    22 Aug 19  2020 ..
drwxr-xr-x. 3 selenium nogroup 24 Mar 19 03:04 .cache
drwx------. 3 selenium nogroup 27 Mar 19 03:04 .config
-rwxr-xr--. 1 selenium nogroup 71 Mar 19 03:04 .fehbg
drwxrwxr-x. 1 root     root    34 Aug 19  2020 .fluxbox
drwxr-xr-x. 3 selenium nogroup 19 Mar 19 03:04 .local
drwxrwxr-x. 2 root     root     6 Aug 19  2020 Downloads
```

**Comment by vania-pooh** [comment]
@andrew-sumner this was already fixed in last 1-2 versions of Chrome. We now have plans to rebuild all images with these fixes. It takes some time.

**Comment by andrew-sumner** [comment]
I've updated helm template (locally) to include chrome 89 as it doesn't currently - that only made things worse.

# chrome-89
```
C:\Work\Selenium\Moon>kubectl logs chrome-89-0-a5494062-3c77-45f4-aa6c-4f18eaef23e6 -c browser
mkdir: cannot create directory '/var/run/pulse': Permission denied
/entrypoint.sh: line 61: /var/run/pulse/pulse/.config/pulse/cookie: No such file or directory
E: [autospawn] core-util.c: Failed to create secure directory (/var/run/pulse/pulse/.config/pulse): No such file or directory
W: [autospawn] lock-autospawn.c: Cannot access autospawn lock.
E: [pulseaudio] main.c: Failed to acquire autospawn lock
Failed to create secure directory (/var/run/pulse/pulse/.config/pulse): No such file or directory
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
Waiting X server...
Waiting X server...
Logging to: /dev/null
Can't create directory /var/run/pulse/.fluxboxmkdir: cannot create directory '/var/run/pulse/.fluxbox': No such file or directory
Waiting X server...
touch: cannot touch '/var/run/pulse/.fluxbox/lastwallpaper': No such file or directory
Starting ChromeDriver 89.0.4389.23 (61b08ee2c50024bab004e48d2b1b083cdbdac579-refs/branch-heads/4389@{#294}) on port 4444
All remote connections are allowed. Use an allowlist instead!
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
feh WARNING: Can't write to /var/run/pulse/.fehbg
/usr/bin/fbsetbg: 159: cannot create /var/run/pulse/.fluxbox/lastwallpaper.tmp: Directory nonexistent
mv: cannot stat '/var/run/pulse/.fluxbox/lastwallpaper.tmp': No such file or directory
/usr/bin/fbsetbg: 168: cannot create /var/run/pulse/.fluxbox/lastwallpaper: Directory nonexistent
[1616137539.884][WARNING]: Deprecated chrome option is ignored: useAutomationExtension
[1616137539.885][WARNING]: Deprecated chrome option is ignored: useAutomationExtension
2021/03/19 07:05:40 failed to create downloads dir: mkdir /var/run/pulse: permission denied
2021/03/19 07:05:42 [INIT] [Listening on :7070]
```

# chrome-88
```
C:\Work\Selenium\Moon>kubectl logs chrome-88-0-a497200a-af0d-492f-953b-57ba55faf884 -c browser
E: [pulseaudio] client-conf-x11.c: xcb_connection_has_error() returned true
xcb_connection_has_error() returned true
21
Waiting X server...
Waiting X server...
Logging to: /dev/null
Waiting X server...
Waiting X server...
Waiting X server...
/usr/bin/fbsetbg: 159: /usr/bin/fbsetbg: cannot create /home/selenium/.fluxbox/lastwallpaper.tmp: Permission denied
mv: cannot stat '/home/selenium/.fluxbox/lastwallpaper.tmp': No such file or directory
/usr/bin/fbsetbg: 168: /usr/bin/fbsetbg: cannot create /home/selenium/.fluxbox/lastwallpaper: Permission denied
Starting ChromeDriver 88.0.4324.27 (6347fe8bf1e48bd0c54d07dc55ca011cf40861c9-refs/branch-heads/4324@{#450}) on port 4444
All remote connections are allowed. Use an allowlist instead!
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[1616137364.699][WARNING]: Deprecated chrome option is ignored: useAutomationExtension
[1616137364.699][WARNING]: Deprecated chrome option is ignored: useAutomationExtension
2021/03/19 07:02:45 [INIT] [Listening on :7070] 
```

**Comment by andrew-sumner** [comment]
Firefox 85 and Edge 90 were essentially a repeat of Chrome 89:

> mkdir: cannot create directory '/var/run/pulse': Permission denied

Just in case this is an issue with my setup, this is how I'm installing Moon:

> helm upgrade --install -n itcrowd-moon moon aerokube/moon -f values.yaml

**values.yaml**
```
moon:
  enabled:
    resources: true

  config:
    kernelCaps: []

  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: moon.k8stest.cloud.westpac.co.nz
      kubernetes.io/external-dns: managed

  timeouts:
    ## Browser pod will be deleted after this timeout, if there was no comminication with it.
    sessionTimeout: 20m

  securityContext:
    runAsUser: 1000
    
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: moon-node
                operator: Exists

  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations:
    - effect: NoSchedule
      key: MoonPods
      operator: Exists

  ## Default free Moon license key for 4 parallel sessions.
  licenseKey: MG1RSVdpc2Z6YjdQQVZjd2lpei9KMkd1T3dzMTFuL1dlRjVSc3NOMUcxZk9QaUxWa3Q5SnBIakIxa09wWm0vVFJqQ0tsa21xVG1OODVRZnlQbjBjVmRHVWFLampTOFF1a3VLRXRPcEUwbnEySG16QWFQWHRDYTVjMm9jZzZFaUJqeFd5ODE4UFBHZzNCNWpCYXlha3oweFBscFl1RnB0V0U1Q3FwOGl5VDdKTk9abG5aSmlPdnRmZDFvSG1nNnVwVXBLV2E4RmYwWHcreERIR29ZTE1XTldPb1hvT2ZCUnZpcDhPWW05a1FqN0hBWWVOYUtLT1lPWlVJa1dsb1gxdjNOT1htTFpZalhsQ3h1Q3V6NWhiQjIwSjVIY0JTYnZybm9zYm14RXFkSFpQWVBKWUlKTzZvVlBnODhQeFErZ1EyTk5sWG82TC9XeXU3aisrNU0rSEdPcXlOSEdlNGx4Zm1nNVhjMWlnNkN1OCtNSVVYRzNqUllqOUY4ZHdReWpSbFNMNmFpL2dRQnc3TzY0U0lwdVF2d29jYi9kVzFSYWFRVkd3ZXYrOVdING8zRWRrYkVONUhRTmQ2MUxsUnFNdmtKeWVHV21tVlVUZ2dsMDRsTFFLTmZNVG81L2JVakNBMGhNeER5VHNJdmVRRGFMMklvTWpvcFk4VERlK1U2bUJvUDVxNVYrcCtDQVhjbjYxQlRaUVp0bmNqL0JBVkdNOEZ4NW9rWHRYSVAxUkY0a1VCckZVTDFyTWF1VkZqSk5xU1pLT293dUpMTTg2SEZ0Sld0eUlRK3ZZZm1pZU0xM292MnVleDBoRlhRdFkvMkt1dUhhN3dKV2pFT0pqaEVzTjhXSy82ZlFFbi9EQzcrNkw3NzhlbmVVZ2lLZ3VFbjlMMXZMYVZ5VWtQaWc9O2V5SnNhV05sYm5ObFpTSTZJa1JsWm1GMWJIUWlMQ0p3Y205a2RXTjBJam9pVFc5dmJpSXNJbTFoZUZObGMzTnBiMjV6SWpvMGZRPT0=
```

**Comment by aandryashin** [comment]
If you add kernel capability SYS_ADMIN, everything should start working...
If it is restricted you have to add environment variable HOME=/tmp to avoid
permission denied errors...

пт, 19 мар. 2021 г., 10:37 andrew-sumner ***@***.***>:

**Comment by andrew-sumner** [comment]
Thanks for the advice. It is working but has lead to a few other questions. Apologies if this isn't the correct place to be asking these questions.

In reply to the last post: If I remove SYS_ADMIN everything breaks because of how locked down our environment is.

1. Adding HOME=/tmp works, however to implement it I ended up overriding the default list of browsers provided by helm by adding customQuota, is there an easier way to do this with helm?

```
  customQuota:
    browsers:
      safari:
        default: "13.0"
        versions:
          "13.0":
            image: browsers/safari:13.0
            port: "4444"
            path: "/"
            env: [ "HOME=/tmp" ]
```

2. I'm unable to start the Edge browser (version 90). Do you have any idea what this error might be caused by?

```
OpenQA.Selenium.WebDriverException: 'unknown error: MSEdge failed to start: crashed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from msedge location /usr/bin/microsoft-edge is no longer running, so MSEdgeDriver is assuming that MSEdge has crashed.)'
```

3. The "Create Session" button on the UI  doesn't work - the button eventually turns red. I cannot find any logs that would give the reason this is failing. The only thing I have spotted is that the "More capabilites" option in the UI always contains:

```
{
  "operaOptions": {
    "binary": "/usr/bin/opera"
  }
}
```
