### ISSUE TITLE
¿It is possible to save videos on S3 with aws-iam-authenticator?

### ISSUE THREAD

**Issue by Juancarlosmartin10** [aerokube/moon#273]
I deployed a moon app on a Kubernetes cluster, but I can not see the videos.

It is possible to save videos o a PVC or on a S3 with aws-iam-authenticator?

**Comment by vania-pooh** [comment]
@Juancarlosmartin10 yes, we have alternatives but not yet documented images. Instead of `aerokube/moon-video-recorder`, simply user `aerokube/aws-video-recorder` and instead of `aerokube/logger` use `aerokube/aws-logger`. How to override system images in `service.json` is described here: https://aerokube.com/moon/latest/#custom-docker-registry

**Comment by Juancarlosmartin10** [comment]
@vania-pooh And it is possible to save videos on a PVC in Kubernetes?¿

**Comment by vania-pooh** [comment]
@Juancarlosmartin10 no, only S3 is supported.

**Comment by Juancarlosmartin10** [comment]
Hi Vania, 

Do you have an example of configuratios for this image, specifically how can I say to aerokube/aws-video-recorder and to aerokube/aws-video-recorder where is my aws-authenticator. 

Thanks in advance

**Comment by vania-pooh** [comment]
@Juancarlosmartin10 what we support is AWS S3 role-based access:

1. Add AWS role using the following CloudFormation template:

```
#jinja2:trim_blocks: False
#jinja2:lstrip_blocks: False
{% set var = config.jinja_parameters %}
AWSTemplateFormatVersion: '2010-09-09'

Description: Contains infra components for Aerokube Moon
Parameters:
  TargetBucket:
    Description: Target bucket for IAM permissions
    Type: String
Resources:
  PodRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: aerokube-moon
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Action: sts:AssumeRole
          Principal:
            Service: ec2.amazonaws.com
        - Effect: Allow
          Action: sts:AssumeRole
          Principal:
            AWS: !Sub arn:aws:iam::${AWS::AccountId}:role/EKSInstanceRole
      Policies:
        - PolicyName: aerokube-moon
          PolicyDocument:
            Statement:
              - Action:
                  - s3:List*
                  - s3:Get*
                  - s3:Put*
                Effect: "Allow"
                Resource:
                  - !Sub "arn:aws:s3:::${TargetBucket}/*"
                  - !Sub "arn:aws:s3:::${TargetBucket}"
```

2. Annotate Moon namespace with the following annotation:

```
annotations:
  iam.amazonaws.com/allowed-roles: |
    ["aerokube-moon"]
```

3. Set any non-empty values to S3 `accessKey` and `secretKey` values.

```
s3:
  endpoint: https://s3.eu-west-1.amazonaws.com
  bucketName: <your-bucket>
  version: S3v4
  accessKey: "any-value"
  secretKey: "any-value"
```

4. [Use](https://aerokube.com/moon/latest/#_using_custom_docker_registry) role-compatible images for logger and video recorder:

```
images:
  logger:
    image: aerokube/aws-logger:1.7.1
  videoRecorder:
    image: aerokube/aws-video-recorder:1.7.1
```

5. [Add](https://aerokube.com/moon/latest/#_using_custom_kubernetes_annotations) an annotation to browser pods:

```
annotations:
  iam.amazonaws.com/role: aerokube-moon
```

Resulting `service.json` file should look like the following:

```json
{
  "s3": {
    "endpoint": "https://s3.eu-west-1.amazonaws.com",
    "bucketName": "<your-bucket>",
    "version": "S3v4",
    "accessKey": "any-value",
    "secretKey": "any-value"
  },
  "images": {
    "logger": {
      "image": "aerokube/aws-logger:1.7.1"
    },
    "videoRecorder": {
      "image": "aerokube/aws-video-recorder:1.7.1"
    }
  },
  "annotations": {                                 
    "iam.amazonaws.com/role": "aerokube-moon"
  }
}
```
