### ISSUE TITLE
Moon failed to copy videos to S3 Minio local bucket

### ISSUE THREAD

**Issue by harbesh** [aerokube/moon#303]
Problem: after recording video it couldn't be copied to the bucket.
How it could be solved?

<h3>Moon</h3>

Deployed moon version 1.9.4 with necessary credentials:
```
...
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: moon
stringData:
  s3.accessKey: "minioadmin"
  s3.secretKey: "minioadmin"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: moon
data:
  service.json: |
    {
      "kernelCaps": [ "SYS_ADMIN" ],
      "s3": {
        "endpoint": "http://video-minio.{{cluster-domain}}",
        "bucketName": "moon-test",
        "version": "s3v4"
      },
      "images": {
        "defender": {
          "image": "{{docker-registry}}/aerokube/defender:1.9.4"
        },
        "logger": {
          "image": "{{docker-registry}}/aerokube/logger:1.9.4"
        },
        "videoRecorder": {
          "image": "{{docker-registry}}/aerokube/moon-video-recorder:1.9.4"
        }
      }
    }
...
```

S3 was initialised correctly:
```
2022/01/18 15:12:39 [INIT] [Will add kernel capability "SYS_ADMIN" to every browser pod]
2022/01/18 15:12:39 [INIT] [Will upload data to S3 storage with the following parameters: endpoint = http://video-minio.<local-subdomains>, bucketName = moon-test, version = s3v4]
```

<h3>Logs</h3>

- logger
```
Added `s3` successfully.
mc: <ERROR> Unable to write to one or more targets. Bucket `moon-test` does not exist. 
```

- video-recorder
```
Command [ffmpeg -f pulse -i default -y -nostdin -f x11grab -draw_mouse 0 -video_size 1920x1080 -r 20 -i localhost:99 -codec:v mpeg4 -pix_fmt yuv420p -filter:v pad=ceil(iw/2)*2:ceil(ih/2)*2 /tmp/ae9316a7-02be-44af-b3bb-47e3acd2bbf5.mp4] finished with status: exit status 255
`/tmp/ae9316a7-02be-44af-b3bb-47e3acd2bbf5.mp4` -> `s3/moon-test/chrome-96-0-6c9e940f-88cd-412f-9cf6-197c19964793/ae9316a7-02be-44af-b3bb-47e3acd2bbf5.mp4`
Total: 0 B, Transferred: 0 B, Speed: 0 B/s
mc: <ERROR> Failed to copy `/tmp/ae9316a7-02be-44af-b3bb-47e3acd2bbf5.mp4`. Bucket `moon-test` does not exist.
Command [mc --quiet cp /tmp/ae9316a7-02be-44af-b3bb-47e3acd2bbf5.mp4 s3/moon-test/chrome-96-0-6c9e940f-88cd-412f-9cf6-197c19964793/ae9316a7-02be-44af-b3bb-47e3acd2bbf5.mp4] finished with status: exit status 1 
```

<h3>Minio</h3>

minio.yml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: video-minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-minio
spec:
  selector:
    matchLabels:
      app: video-minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: video-minio
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: video-minio
      containers:
        - name: minio
          volumeMounts:
            - name: data
              mountPath: "/data"
          image: "{{docker-registry}}/bitnami/minio:latest"
          env:
            - name: MINIO_ROOT_USER
              value: "{{minio-access-key}}"
            - name: MINIO_ROOT_PASSWORD
              value: "{{minio-secret-key}}"
          ports:
            - name: api
              containerPort: 9000
            - name: console
              containerPort: 9001
          resources:
            requests:
              cpu: "0.1"
              memory: "100Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
          startupProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            failureThreshold: 60
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            periodSeconds: 60
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /minio/health/ready
              port: 9000
            periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: video-minio
  labels:
    app: video-minio
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 9000
    - name: console
      port: 9001
  selector:
    app: video-minio

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: kong
    konghq.com/strip-path: "true"
  name: video-minio
  labels:
    app: video-minio
spec:
  rules:
    - host: video-minio.{{cluster-domain}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: video-minio
                port:
                  number: 9000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: kong
    konghq.com/strip-path: "true"
  name: video-minio
  labels:
    app: video-minio
spec:
  rules:
    - host: video-minio-ui.{{cluster-domain}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: video-minio
                port:
                  number: 9001

```
Bucket exists as local:
![image](https://user-images.githubusercontent.com/42370982/149973710-ef3cc38b-3740-400c-a5e7-a3b83b5f2ca5.png)
