### ISSUE TITLE
Browser pods not termitating

### ISSUE THREAD

**Issue by yurii-kryvosheia** [aerokube/moon#429]
We are noticing numerous Chrome browser pods that are left running without termination.

Steps to reproduce:
1. Run tests
2. Wait for the browser pods to appear
3. Restart the moon pod using the command `kubectl -n moon rollout restart deployment moon` or delete the pods.
4. Stop tests

If you repeat these steps from the beginning, you will see an increasing number of idle, unterminated pods that need to be manually deleted. These pods are visible in the UI.

**Comment by aandryashin** [comment]
Please check logs for defender container in browser pod, browser pods
should be timed out in 5min by default, if not there should be error
messages in defender container logs.

пт, 9 авг. 2024 г., 10:53 yurii-kryvosheia ***@***.***>:

**Comment by yurii-kryvosheia** [comment]
@aandryashin 
What if we don't have "defender" container? 🤔 Just a "ca-certs" and a "browser".

**Comment by aandryashin** [comment]
That is not possible, every browser pod has defender container running.

пт, 9 авг. 2024 г., 15:57 yurii-kryvosheia ***@***.***>:

**Comment by yurii-kryvosheia** [comment]
Here's the values for the moon2 chart, version 2.7.1. Nothing fancy.
```
    licenseSecretName: moon-license
    deployment:
      experimentalUI: true
      nodeSelector:
        scope: "moon"
      tolerations:
        - key: "Moon"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"

    customIngress:
      enabled: true
      annotations:
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/healthcheck-path: /ui/
        alb.ingress.kubernetes.io/success-codes: 200,201,404
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
      ingressClassName: "ops"
      host: "moon.domain.com"
      paths:
        - path: /wd/hub
          port: 4444
        - path: /playwright
          port: 4444
        - path: /devtools
          port: 4444
        - path: /api
          port: 9090
        - path: /ui
          port: 9090
    ingress:
      enabled: false

    browsers:
      default:
        annotations:
          karpenter.sh/do-not-disrupt: "true"
        nodeSelector:
          scope: "moon"
        tolerations:
          - key: "Moon"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
```
And that's how browser pod looks like
<img width="1125" alt="image" src="https://github.com/user-attachments/assets/38b03bbe-5411-4557-ab0d-c13f79a60c85">
What could possibly be the issue?
