### ISSUE TITLE
Couldn't upload video to Minio S3 after updating to 2.7

### ISSUE THREAD

**Issue by evheniyt** [aerokube/moon#432]
After updating moon to version 2.7.1 we found that the recorded video couldn't be uploaded to S3 on Minio.

Error:
```
video-recorder 2024/09/22 14:56:11 upload: operation error S3: PutObject, https response error StatusCode: 0, RequestID: , HostID: , request send failed, Put "http://moon.ci-infrastructure-minio.ci-infrastructure.svc.cluster.local:9000/chrome-125-0-df6a7edc-d951-4a6d-83ac-57fc2affc846/video.mp4?x-id=PutObject": dial tcp: lookup moon.ci-infrastructure-minio.ci-infrastructure.svc.cluster.local on 10.96.0.10:53: no such host 
```

Everything works fine on version 2.6.1
```
video-recorder Completed 256.0 KiB/366.8 KiB (23.3 MiB/s) with 1 file(s) remainingCompleted 366.8 KiB/366.8 KiB (9.3 MiB/s) with 1 file(s) remaining upload: Downloads/video.mp4 to s3://moon/chrome-125-0-0ec133e0-e503-4f9c-8b15-fec14b0e60a2/video.mp4
```

Config:
```yaml
      storage:
        endpoint: http://ci-infrastructure-minio.ci-infrastructure.svc.cluster.local:9000
        bucket: moon
        accessKey: "minio"
        secretKey: "minio"
        metadata: false
```
