### ISSUE TITLE
Moon2 TLS not working

### ISSUE THREAD

**Issue by Vsetecka7** [aerokube/moon#435]
Hi, I have a problem with generating routes in Openshift from ingress **while having TLS enabled**.

**Value file**
```
ingress:
 enabled: true

 host: moon2.apps.foo.bar

 ingressClassName: nginx

 tlsCert: baz
 
 tlsKey: qux

 tlsSecretName: moon2-tls-cert
 
 openshift: true
```

When I try to create route for single path with given cert and key, it works, so certs should be fine (SAN is correct too):
```
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: moon2-secure
  namespace: moon2
spec:
  host: moon2.apps.foo.bar
  path: /
  to:
    kind: Service
    name: moon2
  port:
    targetPort: 8080
  tls:
    termination: edge
    certificate: |
      baz
    key: |
      qux
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
```

Ingress without tls block works fine too, but just for HTTP.
```
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: moon2
  namespace: moon2
spec:
  ingressClassName: openshift-default
  rules:
    - host: moon2.apps.foo.bar
      http:
        paths:
          - path: /ui
            pathType: Prefix
            backend:
              service:
                name: moon2
                port:
                  number: 9090
...
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: moon2
                port:
                  number: 4444
status:
  loadBalancer: {}
```
When I add this block:
```
  tls:
    - hosts:
        - moon2.apps.foo.bar
      secretName: moon2-tls-cert
```
It doesn't create routes and IngressController's logs are empty.

Does anyone else have/had this problem?

Moon2 version: 2.7.2
