### ISSUE TITLE
S3 (GCS) missing bucket in upload - 2.6.2 -> 2.7.2

### ISSUE THREAD

**Issue by toby181** [aerokube/moon#436]
After updating moon2 from 2.6.2 to 2.7.2 the s3 upload to GCS (Google Cloud Storage) is failing with the exception "upload: operation error S3: PutObject, https response error StatusCode: 403, RequestID: , HostID: , api error SignatureDoesNotMatch: Access denied.".
The authentication / authorization itself is not the issue as it is working with 2.6.2 and also verified separately.

Comparing the logs of the video-recorder container shows that the bucket `moon-recordings` seems to be missing in the upload command:

2.7.2
```
2025/02/10 12:36:15 uploading to s3://chrome-129.0-2025-02-10/myvideo.20250210.1336.mp4
...
Exiting normally, received signal 2.
2025/02/10 12:39:31 upload: operation error S3: PutObject, https response error StatusCode: 403, RequestID: , HostID: , api error SignatureDoesNotMatch: Access denied.
```

2.6.2
```
Exiting normally, received signal 15.
Uploading /home/user/Downloads/myvideo.20250210.1322.mp4 to s3://moon-recordings/chrome-129.0-2025-02-10/myvideo.20250210.1322.mp4
upload: Downloads/myvideo.20250210.1322.mp4 to s3://moon-recordings/chrome-129.0-2025-02-10/myvideo.20250210.1322.mp4
```

This is the HelmRelease that we're using (simplified). We do not configure the container image tags as they're extracted from the HelmChart. Just the chart version is changed from 2.6.2 to 2.7.2.
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &name moon2
  namespace: moon
spec:
  releaseName: *name
  chart:
    spec:
      chart: moon2
      version: 2.7.2
      sourceRef:
        kind: HelmRepository
        name: ...
        namespace: ...
  install:
    crds: "CreateReplace"
  upgrade:
    crds: "CreateReplace"
  values:
    ...
    configs:
      default:
        containers:
          ca-certs:
            repository: quay.io/aerokube/ca-certs
          proxy:
            repository: quay.io/aerokube/tinyproxy
          defender:
            repository: quay.io/aerokube/defender
          video-recorder:
            repository: quay.io/aerokube/video-recorder
          vnc-server:
            repository: quay.io/aerokube/x11vnc
          window-manager:
            repository: quay.io/aerokube/openbox
          x-server:
            repository: quay.io/aerokube/xvfb
        storage:
          bucket: "moon-recordings"
          endpoint: "https://storage.googleapis.com"
          filename: ""
          pattern: "$browserName-$browserVersion-$date"
          noProxy: "..."
          httpProxy: ""
          httpsProxy: "..."
          metadata: false
          secretRef:
            accessKey: "accessKey"
            secretKey: "secretKey"
            name: moon-recordings-credentials
    deployment:
      replicas: 1
      moonRepo: quay.io/aerokube/moon
      moonConfRepo: quay.io/aerokube/moon-conf
      moonUIRepo: quay.io/aerokube/moon-ui
      ...
    browsers:
      default:
        ...
```
