### ISSUE TITLE
Move Openshift deployment to a repository

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/moon#66]
Remove from docs and create a one-command installation repository.

**Comment by vania-pooh** [comment]
To work with CAP_SYS_ADMIN need to add:
```
$ oc adm policy add-scc-to-user  privileged -z default -n moon
```

**Comment by sakharovmaksim** [comment]
Наша реализация yaml-файла для OpenShift (вставить сам файл нельзя, выкладываю текстом):
[moon-openshift-yaml.txt](https://github.com/aerokube/moon/files/3039640/moon-openshift-yaml.txt)

Что нужно сделать руками:
1. Настраиваем доступ для сервис-аккаунта
`oc policy add-role-to-user edit system:serviceaccount:moon:default`

Проверить выполненную операцию:
`oc get rolebindings edit -o yaml`

2. Создаем Secret с пользователями
`oc create secret generic users --from-file=./users.htpasswd`

3. Создаем ConfigMap с квотой для пользователей
`oc create configmap quota --from-file=./quota`

4. Выдаем необходимые права подам браузеров (нужен админский доступ к кластеру)
`oc adm policy add-scc-to-user privileged -z default -n moon`

5. Создаем темплейт
`oc create -f moon-openshift.yaml -n moon`

6. Запускаем в OpenShift деплоймент проекта, смотрим за ходом процесса...

7. Настраиваем роутинг для всех сервисов, чтобы сервисы стали доступны из вне кластера
<img width="915" alt="Routing" src="https://user-images.githubusercontent.com/17139166/55534287-a692f500-56bc-11e9-9f27-1c98b501ea1c.png">

UPD: Добавил настройку роутинга

**Comment by vania-pooh** [comment]
@sakharovmaksim could you try the following file: https://github.com/aerokube/moon-deploy/blob/master/moon-openshift.yaml ? If it works - will update Moon docs then.

**Comment by kuznetsovaOk** [comment]
Hello! We've tried your template in OpenShift and it seems to be working good.
I've only made a couple of additions:

1. I've tried to add license key secret with unencrypted key as it is in your template and there was an error in pod logs: 
`[[Failed to reload license: failed to read license from /license/license.key: malformed license data: failed to decode license key: illegal base64 data at input byte 684]]`
I've changed 'data' to 'dataString' in licensekey secret description and then license key was applied perfectly fine. Also I've made the same with users secret.

2. We still had to apply this command 'oc policy add-role-to-user edit system:serviceaccount:moon:default' so maybe it is reasonable to add RoleBinding kind to your template as well. I've made it like this:
```yaml
- apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: edit
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: edit
    subjects:
    - kind: ServiceAccount
      name: default
```

3. I've also added to template the routing rules. Maybe it'll be useful for other users as well.
```yaml
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: moon
    spec:
      port:
        targetPort: moon
      to:
        kind: Service
        name: moon
        weight: 100
      wildcardPolicy: None
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: moon-ui
    spec:
      port:
        targetPort: moon-ui
      to:
        kind: Service
        name: moon
        weight: 100
      wildcardPolicy: None
```

After these three additions to your template we are almost able to apply and use Moon on new project after running only one command. The only thing left to do manually is to allow browsers pods to be run in privileged mode `oc adm policy add-scc-to-user privileged -z default -n moon`
