### ISSUE TITLE
Add note about Openshift router timeout

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/moon#69]
Should add:
```
apiVersion: v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/timeout: 5500ms
```
